export { compileForBuild } from "./src/build/compiler/index.js";
export { discoverRoutes } from "./src/build/compiler/route-discoverer.js";
export { hmr } from "./src/client/hmr-runtime.js";
export { buildProduction } from "./src/build.js";
export { optimizeImages } from "./src/build/image-optimizer.js";
export { SSRRouter } from "./src/router/SSRRouter.js";
export { default as logger } from "./src/logger/logger.js";
export { program } from "./src/cli.js";
export { analyzeBuild } from "./src/analyzer/index.js";
export { createDevHandler } from "./src/server/dev-handler.js";
export { startDevServer } from "./src/server/dev-server.js";
export const version: "1.2.2";
export { compileProject, compileFile } from "./src/client/compiler.js";
export { optimizeImage, optimizeImagesBatch, hasWasm, version as optimizerVersion } from "./src/image-optimizer/index.js";
export { Router, Link, useRouter } from "./src/router/index.js";
export { loadConfig, defaultConfig } from "./src/config/index.js";
export { MiddlewareManager, loadMiddleware, runMiddleware, MiddlewareContext } from "./src/middleware/index.js";
export { discoverLayouts, compileLayouts, matchLayout, generateLayoutWrapper, injectLayoutsIntoRouter } from "./src/layouts/index.js";
export { discoverLoadingComponents, compileLoadingComponents, generateLoadingAwareRouter, getLoadingScript, DEFAULT_LOADING_HTML } from "./src/loading/index.js";
export { needsHydration, getInteractiveFeatures, analyzeRoutes, generatePartialHydrationCode, logHydrationReport } from "./src/hydration/index.js";
export { scaffold, parseCreateArgs } from "./src/scaffolder/index.js";
export { minifyCSS, combineCSS } from "./src/css/processor.js";
export { copyImagesSync, isImageFile } from "./src/images/index.js";
export { extractStaticHTML, isServerIsland, validateServerIsland } from "./src/server-islands/index.js";
export { buildAliasMap, rewriteAliasImports, getAliasDirs } from "./src/utils/importhow.js";
//# sourceMappingURL=index.d.ts.map